### ISSUE TITLE
understand a line of .htaccess

### ISSUE THREAD

**Issue by NGOAUAN** [sergeychernyshev/.htaccess#20]
Hello I need your help to understand this: ^(.*)\.(\d+)(_m_\d+)?\.([^\.]+)$

Thanks for your help

**Comment by sergeychernyshev** [comment]
It is a regex that accounts for a versioned and timestamped version of the file rewriting it to point at the regular filename in order to serve the latest version - see comment here: https://github.com/sergeychernyshev/.htaccess/blob/master/.htaccess#L109-L110

If you use a different pattern for fingerprinting in your filenames, feel free to modify this regular expression.
